homepage:
  path: /
  controller: App\Controller\HomeController::index

register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::app_verify_email

login:
  path: /login
  controller: App\Controller\SecurityController::login

journee:
  path: /journee/{journee}
  controller: App\Controller\JourneeController::index

add_journee:
  path: /journee/add
  controller: App\Controller\JourneeController::add

add_participant:
  path: /journee/add/participant/{journee}
  controller: App\Controller\JourneeController::addParticipant

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout